# Data Preprocessing

### Data Collection

In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [14]:
df = pd.read_csv("customer_churn_raw.csv")

In [15]:
df.head()

,customer_id,gender,age,tenure_months,contract_type,internet_service,payment_method,monthly_charges,total_charges,support_calls,churn
0,CUST11321,Male,18.0,44,Month-to-month,DSL,Credit card,80.21,3460.21,1,No
1,CUST10419,Female,47.0,2,Month-to-month,DSL,Credit card,130.15,247.61,2,Yes
2,CUST11693,Male,NaN,10,Month-to-month,Fiber optic,Bank transfer,50.51,544.19,2,Yes
3,CUST10141,Male,NaN,4,Month-to-month,DSL,Bank transfer,42.10,176.30,1,No
4,CUST11239,Male,18.0,21,One year,Fiber optic,Credit card,35.96,767.49,1,Yes

In [16]:
df.shape

(2030, 11)

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2030 entries, 0 to 2029
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       2030 non-null   str
 1   gender            2030 non-null   str
 2   age               1969 non-null   float64
 3   tenure_months     2030 non-null   int64
 4   contract_type     2030 non-null   str
 5   internet_service  1990 non-null   str
 6   payment_method    1990 non-null   str
 7   monthly_charges   2030 non-null   float64
 8   total_charges     1950 non-null   float64
 9   support_calls     2030 non-null   int64
 10  churn             2030 non-null   str
dtypes: float64(3), int64(2), str(6)
memory usage: 174.6 KB

In [18]:
df.describe()

,age,tenure_months,monthly_charges,total_charges,support_calls
count,1969.000000,2030.000000,2030.000000,1950.000000,2030.000000
mean,40.844083,19.375862,65.795281,1272.762697,1.856158
std,13.801348,17.766658,32.991111,1422.115237,1.398795
min,18.000000,-47.000000,15.000000,0.000000,0.000000
25%,30.000000,6.000000,44.737500,308.437500,1.000000
50%,40.000000,14.000000,64.665000,799.825000,2.000000
75%,51.000000,28.000000,84.107500,1690.700000,3.000000
max,85.000000,72.000000,501.200000,9195.620000,7.000000

 #### →   Data collection Overview
- There are 11 features and 2030 records
- 6 Str datatype and 5 number datatype columns
- customer_id needs to be removed and other columns will see in next part like duplicates, missing values and handling outliers